backend/hello_world.py, frontend/Dockerfile, frontend/src/App.js
```
docker-compose build
docker-compose up
```
Frontti hakee backin puolelta linkin.
=> add link from backend to frontend

README.md, backend/pages/auth.py
Nyt pitäis palauttaa 401 jos ei mee läpi, onkohan riittävä vai puuttuuko joku oleellinen juttu?
=> add errorhandling to authentication

.github/workflows/main.yml, .gitignore, frontend/README.md, frontend/public/index.html, frontend/robot-tests/login_page.robot, frontend/robot-tests/login_resource.example.robot, frontend/robot-tests/login_resource.py, frontend/robot-tests/requirements.txt, frontend/robot-tests/resource.robot, frontend/src/components/LoginForm.js
Creating the pull request early for possible inputs and ideas.
Robot tests are not yet added to the CI/CD pipeline.
=> Add robot tests to frontend

backend/README.md, backend/requirements.txt, backend/tests/example_test.py
Added example test for backend.
We do not need to test the routes in the backend. Robot tests in frontend are sufficient.
=> Add example pytest for backend

frontend/package-lock.json, frontend/src/App.js, frontend/src/components/LoginForm.js
Invalid login that causes error message.
=> Feat login error

backend/app.py, backend/pages/org.py
Backendin polku `/org` hakee ja palauttaa listan tmc-organisaatioista.
=> Retrieve organization list to backend

frontend/package-lock.json, frontend/package.json, frontend/robot-tests/login_page.robot, frontend/src/App.js, frontend/src/routes/Home.js, frontend/src/routes/Login.js, frontend/src/services/login.js
Added routes:
- directs to login page if not logged in
- directs to "frontpage" if logged in
- user variable not used -> temporarely disabled from eslint with a comment
- added routes directory
=> Feat react router

frontend/src/components/FrontpageForm.js, frontend/src/routes/Home.js, frontend/src/routes/Login.js
=> logout added

frontend/public/index.html, frontend/public/manifest.json, frontend/src/App.js, frontend/src/components/Header.js, frontend/src/components/LogOut.js, frontend/src/routes/Home.js, frontend/src/routes/Login.js, frontend/src/services/auth.js
- added header component
- logout moved to its own component
- fixed authentication checks on all pages
- fixed error message about deleted image logo192.png and logo512.png
=> Feat header component

.github/workflows/main.yml, .gitignore, backend/pages/auth.py, frontend/.eslintrc.js, frontend/README.md, frontend/cypress.config.js, frontend/cypress/e2e/login.cy.js, frontend/cypress/e2e/user_accesses.cy.js, frontend/cypress/fixtures/example.json, frontend/cypress/support/commands.js, frontend/cypress/support/e2e.js, frontend/package-lock.json, frontend/package.json, frontend/src/routes/Login.js, git-hooks/README.md, git-hooks/pre-commit
End-to-end testaaminen lisätty ennen jokaista committia git-hookkina. Ohjeet käyttöönottoon `git-hooks/README.md`.
Branch `feat-init-cypress` yhdistetty tähän oksaan, siitä ei tarvitse tehdä pull requestia.
=> Feat e2e test with hook

frontend/cypress/e2e/organizations.cy.js, frontend/src/routes/Orgs.js
- Frequently used organizations added (Helsingin yliopisto ja MOOC)
- cypress tests added for the feature
=> Feat frequently used orgs

frontend/src/components/Courses.js, frontend/src/components/DeadlineSetting.js, frontend/src/components/Deadlines.js, frontend/src/components/Exercises.js, frontend/src/routes/ExercisePage.js, frontend/src/routes/SettingDeadline.js
- set deadline -sivun komponentit on keskellä sivua
- set deadline -linkki on nyt vain exercises-sivulla
=> Feat setting finishing date

backend/modules/user.py, backend/pages/deadline.py, frontend/src/components/LogOut.js, frontend/src/routes/Login.js, frontend/src/routes/SettingDeadline.js, frontend/src/services/auth.js, frontend/src/services/courses.js, frontend/src/services/deadlines.js, frontend/src/services/org.js
- Change username to user id in database. 
- Remove loggedInUser variable in localstorage
- Renamed localstorage variable 'token' to 'user'
=> User refactoring

backend/tests/database_functions_test.py
backend testiti tietokantakomennoille toimii taas
=> backend tests for database functions fixed

frontend/cypress/e2e/header_and_signout.cy.js, frontend/src/components/Header.js, frontend/src/routes/Login.js
Lisätty login-pageen kuvaus projektista ja fiksattu vähä layouttia samalla sivulla.
=> Feat description

backend/database_functions/deadline_functions.py, backend/modules/user.py, backend/tests/database_functions_test.py
Backend-testit, jotka käyttää tietokantakomentoja, on nyt korjattu.
=> backend tests in the database_functions_test-py-file have been fixed

backend/database_functions/deadline_functions.py, backend/pages/deadline.py, backend/tests/database_functions_test.py, frontend/cypress/e2e/set_deadline.cy.js, frontend/src/components/Deadline.js, frontend/src/components/Deadlines.js, frontend/src/services/deadlines.js
Backendissä on siirretty deadlinen hakeminen tietokannasta omaksi funktioksi ja tälle funktiolle on tehty testi.
Tän jälkeen vois sanoo, et kaikki tohon Tavoitepäivämäärän asettaminen kurssiin -taskiin liittyvät jutut on nyt tehty ja se taski on nyt valmis. Vai keksiikö joku vielä jotain lisättävää tohon taskiin?
=> Finishing the setting deadline task

backend/database_functions/checkpoint_functions.py, backend/tests/database_functions_test.py, frontend/cypress/e2e/set_deadline.cy.js
count_checkpoints laskee nyt checkpointien päivämäärät siten, että jokainen checkpoint on yhtä kaukana sen viereisistä checkpointeista. Myös ensimmäinen checkpoint on yhtä kaukana aloituspäivästä kuin viimeinen checkpoint on deadlinesta, paitsi tilanteessa, jossa päivät eivät mene tasan, niin viimeisen checkpointin ja deadlinen välissä on yksi päivä enemmän kuin aloituspäivän ja ensimmäisen checkpointin välissä.
=> Improving the set checkpoints function

backend/app/models.py, backend/database_functions/checkpoint_functions.py, backend/database_functions/deadline_functions.py, backend/database_functions/user_functions.py, backend/modules/jobs.py, backend/modules/validate.py, backend/pages/auth.py, backend/pages/deadline.py, backend/tests/database_functions_test.py, backend/tests/database_users_test.py, backend/tests/validate_test.py
Updated foreign key settings in tables `deadlines` and `checkpoints`.
=> Add users table

frontend/cypress/e2e/header_and_signout.cy.js, frontend/cypress/e2e/organizations.cy.js, frontend/cypress/e2e/profile.cy.js, frontend/cypress/e2e/set_deadline.cy.js, frontend/package-lock.json, frontend/package.json
Deleted couple of "duplicates" in E2E tests, trying to make the tests run faster
-> E2E test performance improved by 4 % (1min 39s -> 1min 35s)
Most likely better results require mock-TMC-API.
=> Fix refactor e2e tests

backend/app/__init__.py, backend/modules/email.py
- Sähköpostin konfigurointi siirretty `/app/__init__.py` tiedostoon
- Sähköpostit lähtevät nyt omissa säikeissään jolloin sovelluksen pitäisi skaalautua paremmin, jos lähetetään paljon sähköpostia kerralla
- Refaktoroinnin jälkeen onnistuin lokaalisti lähettämään sovelluksesta sähköpostia, mutta mitään useamman sähköpostin lähettämistä säikeissä en testannut
=> Feat async email

README.md, backend/database_functions/user_functions.py, backend/modules/deadline.py, backend/modules/user.py, backend/pages/auth.py, backend/pages/courses.py, backend/pages/deadline.py, backend/tests/database_functions_test.py, frontend/cypress/e2e/set_deadline.cy.js, frontend/public/index.html, frontend/src/services/courses.js, frontend/src/services/deadlines.js
Lisätty kommentteja backendiin.
Backista löytyi yksi käyttämätön route ja funktio, nämä poistettu. Ollut aiemmin käytössä versiossa, jossa oli oma kotisivu. Backista löytyi näemmä myös toinen käyttämätön route sekä frontista vastine. Nämäkin poistettu. Sovellus toimii moitteetta poistojen jälkeen.
Backin yhdessä testissä käytetty myös yhtä poistettua funktiota, testiin vaihdettu toinen käytössä oleva funktio tilalle.
=> comments added to the code

backend/modules/checkpoint.py, frontend/cypress/e2e/set_deadline.cy.js, frontend/src/components/Checkpoints.js
haluttu pistemäärä jokaiselle checkpointille näkyvissä deadline sivulla
=> Checkpoints desired points visible
